language: python
python:
- 2.7
- 3.5
- 3.6
- 3.7-dev
before_install:
- pip install pytest pytest-cov
- pip install coveralls
script:
- stty size
- stty cols 80
- stty size
- pytest
after_success:
- coveralls
env:
- COLUMNS=80
